- name: Configure master node for Kubernetes
  hosts: master
  become: True
  tasks:
  - name: show hostname
    command: hostname
  - name: Set timezone to Asia/Shanghai
    community.general.timezone:
      name: Asia/Shanghai
  - name: Enable NTP
    ansible.builtin.service:
      name: ntp
      enabled: yes
      state: started
  - name: timedatectl set-ntp yes
    shell: /usr/bin/timedatectl set-ntp yes
    tags:
    - enable_ntp_control
  - name: apt update
    apt:
      update_cache: True
  - name: apt upgrade
    apt:
      upgrade: full
  - name: install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: install containerd
    apt:
      name: containerd
  - name: install ipvs dependencies
    apt:
      pkg: 
      - conntrack
      - jq
  - name: Install ipvs
    apt:
      pkg:
      - ipset
      - ipvsadm
      - tgt
  - name: load overlay module
    shell: modprobe overlay
  - name: load br_netfilter module
    shell: modprobe br_netfilter
  - name: copy kubernetes cri configuration file
    copy: 
      src: cfg/99-kubernetes-cri.conf
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
  - name: load kubernetes-cri.conf
    shell: sysctl --system
  - name: import ipvs modules to /etc/modules
    shell: 'ls /lib/modules/$(uname -r)/kernel/net/netfilter/ipvs|grep -o "^[^.]*" >> /etc/modules'
  - name: Enable nf_conntrack_ipv4
    shell: echo nf_conntrack_ipv4 >> /etc/modules