- name: Configure master node for Kubernetes
  hosts: master
  become: True
  tasks:
  - name: show hostname
    command: hostname
  - name: Set timezone to Asia/Shanghai
    community.general.timezone:
      name: Asia/Shanghai
  - name: Enable NTP
    service:
      name: ntp
      enabled: yes
      state: started
  - name: Timedatectl set-ntp yes
    shell: /usr/bin/timedatectl set-ntp yes
    tags:
    - enable_ntp_control
  - name: Apt update
    apt:
      update_cache: True
  - name: Apt upgrade
    apt:
      upgrade: full
  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Install containerd
    apt:
      name: containerd
  - name: Install ipvs dependencies
    apt:
      pkg: 
      - conntrack
      - jq
  - name: Install ipvs
    apt:
      pkg:
      - ipset
      - ipvsadm
      - tgt
  - name: Load overlay module
    shell: modprobe overlay
  - name: Load br_netfilter module
    shell: modprobe br_netfilter
  - name: Copy kubernetes cri configuration file
    copy: 
      src: cfg/99-kubernetes-cri.conf
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
  - name: Load kubernetes-cri.conf
    shell: sysctl --system
  - name: Import ipvs modules to /etc/modules
    shell: 'ls /lib/modules/$(uname -r)/kernel/net/netfilter/ipvs|grep -o "^[^.]*" >> /etc/modules'
  - name: Enable nf_conntrack_ipv4
    shell: echo nf_conntrack_ipv4 >> /etc/modules
  - name: Enable tgt
    systemd:
      name: tgt
      enabled: yes
      state: started
  - name: Enable iscsid
    systemd:
      name: iscsid
      enabled: yes
      state: started
  - name: Disable swap
    shell: swapoff -a && sed -ri 's/.*swap.*/#&/' /etc/fstab
  - name: Disable ufw
    shell: ufw disable
  - name: Reboot
    reboot: